---
- hosts: all
  become: yes
  tasks:
  - name: setup hosts
    copy: src=hosts dest=/etc/hosts

  - name: update repos
    apt: update_cache=true

  - name: install nginx
    apt: pkg=nginx state=installed

  - name: start and enable nginx
    service: name=nginx state=started enabled=yes

  - name: setup nginx
    copy: src=default dest=/etc/nginx/sites-enabled/default

  - name: restart nginx
    service: name=nginx state=restarted
